apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kube-app
  namespace: my-kubernetes
spec:
  template: 
    metadata:
      labels:
        app: kube-app
    spec:
      containers:
        - name: my-app-job
          image: icr.io/ibm_2002/ovya
          ports:
            - containerPort: 80
              protocol: TCP
  selector:
    matchLabels:
      app: kube-app